spring:     
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.10.0.4:3306/natureops
    username: natureops
    password: ENC(ZkQProPN9E+jnhe9I/I0RJ71y1eOKm2BuiwR3jYghNfsuArlujMezdUJrPS1Tj+rQNhZcnKSadpel1urx3yqMw==)
  jpa:
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: file:/usr/local/tomcat/data
  rabbitmq:
    host: 172.10.0.5 
    password: ENC(LEN22Aa3l/21VWGnJW1n5DATuqyXMn7yCcJPuyOYKzVBtWwktaPN0HWiGUAon576VgbwpmCDsI0lgv4HnA+Rl4IFxSWRvUaUGGutay55tPU=)
    port: 5672 
    username: beluga 
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  error:
    page: error
    path: /error
    include-mapping: always
natureops:
  security:
    jwt:
      secret: ENC(9jm6Po+fPKbOqca0xBUw+VP5AZvzyhf2D+wkwqPewds+x2+KLJS31nibobX0hEFXbTf01fvoI4O6/ZlJKhxy3w==)
      issuer: natureops.eus